"""updated chat_message_data

Revision ID: 6dc31e06724f
Revises: 80007365146d
Create Date: 2023-05-01 08:18:04.704900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc31e06724f'
down_revision = '80007365146d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message_data', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('message_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_number', sa.INTEGER(), nullable=True))
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
