"""customer_data table

Revision ID: 6ec0933439db
Revises: 
Create Date: 2023-04-28 14:34:32.029968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec0933439db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message_data')
    op.drop_table('conversation_data')
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_customer_data_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_data_username'))
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('conversation_data',
    sa.Column('conversation_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('conversation_name', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_data.customer_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('chat_message_data',
    sa.Column('conversation_id', sa.INTEGER(), nullable=True),
    sa.Column('message_number', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.TEXT(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_data.conversation_id'], )
    )
    # ### end Alembic commands ###
