"""conversation_data

Revision ID: 80007365146d
Revises: 6ec0933439db
Create Date: 2023-04-28 14:55:10.367515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80007365146d'
down_revision = '6ec0933439db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_data',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('conversation_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_data.customer_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('chat_message_data',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_number', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=8), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_data.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message_data')
    op.drop_table('conversation_data')
    # ### end Alembic commands ###
