"""empty message

Revision ID: e5ba4a74bb0c
Revises: 6dc31e06724f
Create Date: 2023-05-05 09:49:36.143262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ba4a74bb0c'
down_revision = '6dc31e06724f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message_data', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.drop_index('ix_customer_data_username')
        batch_op.create_index(batch_op.f('ix_customer_data_email'), ['email'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_customer_data_email'))
        batch_op.create_index('ix_customer_data_username', ['username'], unique=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('chat_message_data', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
