"""empty message

Revision ID: fccd7b131745
Revises: 29327710a74b
Create Date: 2023-05-19 10:47:54.394220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccd7b131745'
down_revision = '29327710a74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message_data', schema=None) as batch_op:
        batch_op.drop_column('message_number')

    # ### end Alembic commands ###
